### ISSUE TITLE
Add guide howto build it on Debian Jessie

### ISSUE THREAD

**Issue by treaki** [promi/mumble-pluginbot-plusplus#14]
right now i accomplished (on debian 8.6)

```
sudo apt-get install build-essential automake libtool libopus-dev libssl-dev libprotobuf-dev libmpdclient-dev libuv1-dev protobuf-compiler
```
to install the required  dependences

and then done what was in readme and failed because of

```
$ make
make  all-am
make[1]: Entering directory '/home/%username%/git/mumble-pluginbot-plusplus'
  CXX      src/aither/log.lo
g++: error: unrecognized command line option '-std=c++1z'
Makefile:1011: recipe for target 'src/aither/log.lo' failed
make[1]: *** [src/aither/log.lo] Error 1
make[1]: Leaving directory '/home/%username%/git/mumble-pluginbot-plusplus'
Makefile:545: recipe for target 'all' failed
make: *** [all] Error 2

```
you are using something that is not released yet

imho it sould be possible to compile that with any compiler on any posix like system.

thanks

**Comment by promi** [comment]
I will look into it. The GCC compiler (gcc-4.9) on Debian Jessie (8.x) should be able to compile C++14 code (the -std option was still called c++1y, because C++14 support was not complete at that time).

The main problem will probably be that the <experimental/filesystem> library (-lstdc++fs) was not included in GCC before later in the 5.x release cycle.

Currently only a small subset of that library is used (the `path` data type and some functions like `file_exists ()` and `create_directories ()`). It might be feasable to replace them with something that works on gcc-4.9.

**Comment by promi** [comment]
Status update:

I have rewritten a lot of things to work with Jessie on the `develop` branch.

Currently the compilation gets pretty far, but you have to make a few manual adjustments:

- Comment out the `AX_CXX_COMPILE_STDCXX_14([noext], [mandatory])` line in `configure.ac` and rerun `./autogen.sh`.
- Then run configure like this: `CXX='g++ -std=c++1y' ./configure`. That will enable partial C++14 support.
- Then run make as usual.

The compilation should then stop when trying to use `uvw` for the MPD status updater. We will have to write a replacement for that (and can then also get rid of `libuv`). Everything else will probably work.

PS: On a clean VM you have to install the `pkg-config` Debian package in addition to the packages you mentioned.
